'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var SUBMISSIONS_RESET = exports.SUBMISSIONS_RESET = 'SUBMISSIONS_RESET';
var SUBMISSIONS_REQUEST = exports.SUBMISSIONS_REQUEST = 'SUBMISSIONS_REQUEST';
var SUBMISSIONS_SUCCESS = exports.SUBMISSIONS_SUCCESS = 'SUBMISSIONS_SUCCESS';
var SUBMISSIONS_FAILURE = exports.SUBMISSIONS_FAILURE = 'SUBMISSIONS_FAILURE';