import { FormioComponents } from '../FormioComponents';

import address from './address';
import button from './button';
import checkbox from './checkbox';
import columns from './columns';
import container from './container';
import content from './content';
import currency from './currency';
import custom from './custom';
import datagrid from './datagrid';
import datetime from './datetime';
import email from './email';
import fieldset from './fieldset';
import file from './file';
import hidden from './hidden';
import htmlelement from './htmlelement';
import number from './number';
import panel from './panel';
import password from './password';
import phoneNumber from './phoneNumber';
import radio from './radio';
import resource from './resource';
import survey from './survey';
import select from './select';
import selectboxes from './selectboxes';
import signature from './signature';
import table from './table';
import textarea from './textarea';
import textfield from './textfield';
import well from './well';

FormioComponents.register('address', address);
FormioComponents.register('button', button);
FormioComponents.register('checkbox', checkbox);
FormioComponents.register('columns', columns);
FormioComponents.register('container', container);
FormioComponents.register('content', content);
FormioComponents.register('currency', currency);
FormioComponents.register('custom', custom);
FormioComponents.register('datagrid', datagrid);
FormioComponents.register('datetime', datetime);
FormioComponents.register('email', email);
FormioComponents.register('fieldset', fieldset);
FormioComponents.register('file', file);
FormioComponents.register('hidden', hidden);
FormioComponents.register('htmlelement', htmlelement);
FormioComponents.register('number', number);
FormioComponents.register('panel', panel);
FormioComponents.register('password', password);
FormioComponents.register('phoneNumber', phoneNumber);
FormioComponents.register('radio', radio);
FormioComponents.register('resource', resource);
FormioComponents.register('survey', survey);
FormioComponents.register('select', select);
FormioComponents.register('selectboxes', selectboxes);
FormioComponents.register('signature', signature);
FormioComponents.register('table', table);
FormioComponents.register('textarea', textarea);
FormioComponents.register('textfield', textfield);
FormioComponents.register('well', well);
