'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var SUBMISSION_RESET = exports.SUBMISSION_RESET = 'SUBMISSION_RESET';
var SUBMISSION_REQUEST = exports.SUBMISSION_REQUEST = 'SUBMISSION_REQUEST';
var SUBMISSION_SUCCESS = exports.SUBMISSION_SUCCESS = 'SUBMISSION_SUCCESS';
var SUBMISSION_FAILURE = exports.SUBMISSION_FAILURE = 'SUBMISSION_FAILURE';
var SUBMISSION_SAVE = exports.SUBMISSION_SAVE = 'SUBMISSION_SAVE';